# Generated by Django 3.0.3 on 2020-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airlines', models.CharField(max_length=50)),
                ('Source', models.CharField(max_length=20)),
                ('Destination', models.CharField(max_length=20)),
                ('Departure_Time', models.CharField(max_length=10)),
                ('Arrival_Time', models.CharField(max_length=10)),
                ('Seats', models.IntegerField()),
                ('Fare_Type', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
