# Generated by Django 3.0.3 on 2020-04-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airline_Reservation', '0002_reservation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_details',
            name='key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Airline_Reservation.Airplane_Details'),
            preserve_default=False,
        ),
    ]
