# Generated by Django 3.0.3 on 2020-04-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airline_Reservation', '0003_reservation_details_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation_details',
            old_name='Price',
            new_name='Ticket_Price',
        ),
    ]
