# Generated by Django 3.0.3 on 2020-04-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airline_Reservation', '0004_auto_20200407_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_details',
            name='Airlines',
        ),
        migrations.RemoveField(
            model_name='reservation_details',
            name='Arrival_Time',
        ),
        migrations.RemoveField(
            model_name='reservation_details',
            name='Departure_Time',
        ),
        migrations.RemoveField(
            model_name='reservation_details',
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='reservation_details',
            name='Fare_Type',
        ),
        migrations.RemoveField(
            model_name='reservation_details',
            name='Source',
        ),
        migrations.RemoveField(
            model_name='reservation_details',
            name='Ticket_Price',
        ),
    ]
