# Generated by Django 3.0.3 on 2020-04-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airline_Reservation', '0005_auto_20200407_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation_Details',
        ),
    ]
