# Generated by Django 3.0.3 on 2020-04-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airline_Reservation', '0006_delete_reservation_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Flight_Date', models.DateField()),
                ('Returning_Date', models.DateField()),
                ('Adults', models.IntegerField()),
                ('Children', models.IntegerField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline_Reservation.Airplane_Details')),
            ],
        ),
    ]
