# Generated by Django 3.0.3 on 2020-04-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline_Reservation', '0007_reservation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_details',
            name='Children',
            field=models.IntegerField(null=True),
        ),
    ]
