# Generated by Django 3.0.3 on 2020-04-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airline_Reservation', '0008_auto_20200407_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_details',
            name='Adults',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation_details',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservation_details',
            name='Flight_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation_details',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation_details',
            name='Returning_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation_details',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Airline_Reservation.Airplane_Details'),
        ),
    ]
